---
title: "GitHub Projects"
output: 
  prettydoc::html_pretty:
    theme: leonids
    css: styles.css
---

[Home](index.html) | 
[Academic and Professional Experiences](experiences.html) | 
[GitHub Projects](github_projects.html) 

## Project 1: Glioblastoma Multiforme (GBM) Market Analysis [(repository link)](https://github.com/xl3214/m3_GBM_market.git)

This project examines the structure of Glioblastoma Multiforme (GBM) market and existing treatment gaps using information collected from GBM patients. Data provided by Michael Allen Company. For this project, I utilized R version 4.3.1, and R packages `dplyr`, `summarytools`, `forcats`, `tidyverse`, `psych`, `broom`, `knitr`, and `ggplot2`.

You can access the project report [Here](https://github.com/xl3214/m3_GBM_market/blob/a48e0971c2d24c84a469fdbc784a760061bf0ac5/m3_GBM_market.pdf).

## Project 2: NYC Zip Code Level Population Changes [(repository link)](https://github.com/xl3214/p8105_mtp_xl3214.git)

This project examines NYC ZIP code-level population changes using USPS Change of Address (COA) data. You can access the project report [HERE](p8105_mtp_xl3214.html).

## Project 3: Visualization and EDA [(repository link)](https://github.com/xl3214/p8105_hw3_xl3214.git)

This project is broken down to three different smaller projects. It uses data “The Instacart Online Grocery Shopping Dataset 2017” or `instacart`, "Behavioral Risk Factors Surveillance System for Selected Metropolitan Area Risk Trends (SMART) for 2002-2010" or `smart`, and accelerometer data collected on 250 participants in the NHANES study or `accel`. 

For more detailed description of each project, please visit: 

- instacart project [REPORT](instacart_eda.html)
- smart project [REPORT](smart_eda.html)
- accel project [REPORT](accel_eda.html)

## Project 4: Data Cleaning SOP [(repository link)](https://github.com/xl3214/p8105_hw2_xl3214.git)

This project is broken down to three different smaller projects. It uses data “FiveThirtyEight” or `538`, "Mr. Trash Wheel" or `trashwheel`, and dataset collected in an observational study to understand the trajectory of Alzheimer’s disease (AD) biomarkers, or `amyloid`. 

For more detailed description of each project, please visit: 

- 538 project [REPORT](dc_538.html)
- trashwheel project [REPORT](dc_trashwheel.html)
- amyloid project [REPORT](dc_amyloid.html)

## Project 5: Flexdashboard

For this project, I created a flexdashboard using a random sampling of 500 observations of the `instacart` dataset. Click [HERE](p8105_hw4.html) to view. 

## Project 6: Investigating the Association Between Depression and Hypertension [(repository link)](https://github.com/xl3214/depression_hypertension.git)

This is a group project for Application of Epidemiological Research Methods class. Using NHANES 2017 - 2018 data, we analyzed the crude association between binary exposure of Major Depressive Disorder and binary outcome of Hypertension with bivariate logistic regression and Pearson chi-square test. We also included potential confounding variables to assess the adjusted association with multivariable logistic regression and Mantel-Haenszel chi-square test. We calculated the odds ratio and their 95% confidence interval for both crude and adjusted association. 

I was responsible for the research question conceptualization and formalization, conducting literature review, SAS programming for data cleaning, analysis, and error-checking throughout the coding and analyzing process.

You may access the final project abstract [HERE](group15_final_abstract.pdf) and the SAS coding pipeline [HERE](group15_final.sas). 