---
title: "Instacart Visualization using Flexdashboard & Plotly"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
[Home](index.html) | 
[Academic and Professional Experiences](experiences.html) | 
[GitHub Projects](github_projects.html) |
[P8105 HW4](p8105_hw4.html)

## Flexdashboard

```{r setup, message = FALSE, echo = FALSE}
library(flexdashboard)
library(plotly)
library(p8105.datasets)
library(dplyr)

instacart <- p8105.datasets::instacart

# Randomly sample 500 rows for visualization purposes
set.seed(123) # for reproducibility
instacart_sample <- sample_n(instacart, 500)
```

### Line plot of orders over days

```{r line plot, message = FALSE, warning = FALSE, echo = FALSE}
# Line plot of orders over days
orders_by_day <- instacart |>
  mutate(order_dow = factor(order_dow, 
                            levels = 0:6, 
                            labels = c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"), 
                            ordered = TRUE)) |>
  group_by(order_dow) |>
  summarise(num_orders = n())

plot_ly(orders_by_day, 
        x = ~order_dow, 
        y = ~num_orders, mode = 'lines', type = 'scatter', 
        color = 'rgba(220, 20, 60, 0.6)',
        marker = list(size = 10, color = 'rgba(220, 20, 60, 0.6)')) |>
  layout(title = "Orders Over Days of the Week", 
         xaxis = list(title = 'Days of the Week'),
         yaxis = list(title = 'Number of Items Purchased'),
         margin = list(l = 100))
```

### Bar plot of orders by department over days of week

```{r barplot, message = FALSE, warning = FALSE, echo = FALSE}
# Bar plot of orders by department over days of week
department_for_plot <- instacart |> 
  mutate(order_dow = factor(order_dow, 
                            levels = 0:6, 
                            labels = c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"), 
                            ordered = TRUE)) |>
  group_by(department, order_dow) |>
  tally()

plot_ly(data = department_for_plot,
        x = ~n,
        y = ~department,
        color = ~as.factor(order_dow),
        type = 'bar',
        orientation = 'h') |>
  layout(title = "Department Barplot",
         xaxis = list(title = "Number of Items Purchased"),
         yaxis = list(title = "Department"),
         barmode = 'stack', 
         legend = list(title = list(text = '<b>Days of the Week</b>')))
```

### Scatter plot of orders by aisle over days of week

```{r Scatter, message = FALSE, warning = FALSE, echo = FALSE}
# Scatter plot of the number of items ordered in each aisle
aisle_for_plot <- instacart |> 
  mutate(order_dow = factor(order_dow, 
                            levels = 0:6, 
                            labels = c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"), 
                            ordered = TRUE)) |>
  group_by(aisle, order_dow) |>
  summarize(n_obs = n())

aisle_for_plot |>
  plot_ly(
    x = ~n_obs,
    y = ~aisle,
    color = ~as.factor(order_dow),
    type = 'scatter',
    mode = 'markers',
    marker = list(size = 10)
  ) |>
  layout(
    title = "Aisle Scatterplot",
    xaxis = list(title = 'Number of Items Purchased'),
    yaxis = list(title = 'Aisle'),
    margin = list(l = 100), 
    legend = list(title = list(text = '<b>Days of the Week</b>')))
```